services:
  - type: web
    name: hologram
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: BIT_PG_NAME
        sync: false
      - key: BIT_PG_HOST
        sync: false
      - key: BIT_PG_PORT
        sync: false
      - key: BIT_PG_USER
        sync: false
      - key: BIT_PG_PSSWD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
